### PR TITLE
Added demo notebook for running on image pair

### PR DESCRIPTION
**Pull request by ignacio-rocco**
I created a demo notebook for evaluation on image pairs. Contrary to the original method, the normalization of keypoint coordinates is done without using the camera focal length for simplicity.

You can check the produced output [here](https://github.com/ignacio-rocco/learned-correspondence-release/blob/master/demo.ipynb).

### CODE REVIEW

**Comment by kmyid** [comment]
Thank you Ignacio ;) @weiweisun2018 Is the way Ignacio normalized the same as we did for the ACNe paper?

**Comment by weiweisun2018** [comment]
Yup, it is the same as what we did in ACNe paper.

**Comment by kmyid** [comment]
@ignacio-rocco Can you perhaps add a note on the normalization that you should use intrinsics if you have it? If it's not too much work though.

Cheers,
Kwang

**Comment by ignacio-rocco** [comment]
> Can you perhaps add a note on the normalization that you should use intrinsics if you have it? 
Sure, no problem.

I wonder if I also need to remove all matches with negative scores in the following way:

```
# resort matches according to model output
sorted_idx = np.argsort(-ys).squeeze()
kp1  = kp1[sorted_idx,:]
kp2  = kp2[sorted_idx,:]
scores = ys.squeeze()[sorted_idx]

# filter out matches with negative scores
keypoints_a = keypoints_a[scores>0]
keypoints_b = keypoints_b[scores>0]
scores = scores[scores>0]
```

**Comment by kmyid** [comment]
Ah yes you should. I would also add ransac after running the model, but for that, @weiweisun2018  could do it. He needs to probably put an example for his repo as well.

**Comment by ignacio-rocco** [comment]
Ok, I added a new commit addressing the issues discussed

**Comment by kmyid** [comment]
Thank you so much!

**Pull request merged**
